// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_ForumOperations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package TP1;

public interface _ForumOperations
{
    String getTheme(Ice.Current __current);

    String getModerator(Ice.Current __current);

    void postMessage(Message m, Ice.Current __current)
        throws Reject;

    Message getMessage(String title, Ice.Current __current)
        throws Reject;

    void removeMessage(String title, Ice.Current __current)
        throws Reject;

    Message[] getMessages(Ice.Current __current);
}
