// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_ForumOperationsNC.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package TP1;

public interface _ForumOperationsNC
{
    String getTheme();

    String getModerator();

    void postMessage(Message m)
        throws Reject;

    Message getMessage(String title)
        throws Reject;

    void removeMessage(String title)
        throws Reject;

    Message[] getMessages();
}
