// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_ForumDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package TP1;

public interface _ForumDel extends Ice._ObjectDel
{
    String getTheme(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    String getModerator(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    boolean postMessage(Message m, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    Message getMessage(String title, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    boolean removeMessage(String title, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    Message[] getMessages(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
