// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ForumPrxHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package TP1;

public final class ForumPrxHolder
{
    public
    ForumPrxHolder()
    {
    }

    public
    ForumPrxHolder(ForumPrx value)
    {
        this.value = value;
    }

    public ForumPrx value;
}
