// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ForumPrx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package TP1;

public interface ForumPrx extends Ice.ObjectPrx
{
    public String getTheme();

    public String getTheme(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTheme();

    public Ice.AsyncResult begin_getTheme(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTheme(Ice.Callback __cb);

    public Ice.AsyncResult begin_getTheme(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTheme(Callback_Forum_getTheme __cb);

    public Ice.AsyncResult begin_getTheme(java.util.Map<String, String> __ctx, Callback_Forum_getTheme __cb);

    public String end_getTheme(Ice.AsyncResult __result);

    public String getModerator();

    public String getModerator(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getModerator();

    public Ice.AsyncResult begin_getModerator(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getModerator(Ice.Callback __cb);

    public Ice.AsyncResult begin_getModerator(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getModerator(Callback_Forum_getModerator __cb);

    public Ice.AsyncResult begin_getModerator(java.util.Map<String, String> __ctx, Callback_Forum_getModerator __cb);

    public String end_getModerator(Ice.AsyncResult __result);

    public void postMessage(Message m)
        throws Reject;

    public void postMessage(Message m, java.util.Map<String, String> __ctx)
        throws Reject;

    public Ice.AsyncResult begin_postMessage(Message m);

    public Ice.AsyncResult begin_postMessage(Message m, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_postMessage(Message m, Ice.Callback __cb);

    public Ice.AsyncResult begin_postMessage(Message m, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_postMessage(Message m, Callback_Forum_postMessage __cb);

    public Ice.AsyncResult begin_postMessage(Message m, java.util.Map<String, String> __ctx, Callback_Forum_postMessage __cb);

    public void end_postMessage(Ice.AsyncResult __result)
        throws Reject;

    public Message getMessage(String title)
        throws Reject;

    public Message getMessage(String title, java.util.Map<String, String> __ctx)
        throws Reject;

    public Ice.AsyncResult begin_getMessage(String title);

    public Ice.AsyncResult begin_getMessage(String title, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMessage(String title, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMessage(String title, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMessage(String title, Callback_Forum_getMessage __cb);

    public Ice.AsyncResult begin_getMessage(String title, java.util.Map<String, String> __ctx, Callback_Forum_getMessage __cb);

    public Message end_getMessage(Ice.AsyncResult __result)
        throws Reject;

    public void removeMessage(String title)
        throws Reject;

    public void removeMessage(String title, java.util.Map<String, String> __ctx)
        throws Reject;

    public Ice.AsyncResult begin_removeMessage(String title);

    public Ice.AsyncResult begin_removeMessage(String title, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeMessage(String title, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeMessage(String title, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeMessage(String title, Callback_Forum_removeMessage __cb);

    public Ice.AsyncResult begin_removeMessage(String title, java.util.Map<String, String> __ctx, Callback_Forum_removeMessage __cb);

    public void end_removeMessage(Ice.AsyncResult __result)
        throws Reject;

    public Message[] getMessages();

    public Message[] getMessages(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMessages();

    public Ice.AsyncResult begin_getMessages(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMessages(Ice.Callback __cb);

    public Ice.AsyncResult begin_getMessages(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMessages(Callback_Forum_getMessages __cb);

    public Ice.AsyncResult begin_getMessages(java.util.Map<String, String> __ctx, Callback_Forum_getMessages __cb);

    public Message[] end_getMessages(Ice.AsyncResult __result);
}
